name: enumerated
description: A dart package which provides utilities araound dart enums like an EnumSet. 
version: 0.1.1
homepage: https://begnis.dev
repository: https://github.com/Dimibe/enumerated

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

