name: enumerated
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://begnis.dev

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  meta: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

